---
- name: InfluxDB2 - Ensure InfluxDB is up and running
  ansible.builtin.command: influx ping \
    --host "{{ influxdb2_host }}"
  retries: 10
  delay: 5
  register: _ping
  until: _ping.rc == 0
  changed_when: false

- name: InfluxDB2 - Set InfluxDB default user, organization, and bucket
  ansible.builtin.command: influx setup \
    --host "{{ influxdb2_host }}" \
    --org {{ influxdb2_primary_org }} \
    --bucket {{ influxdb2_primary_bucket }} \
    --username {{ influxdb2_primary_username }} \
    --password {{ influxdb2_primary_password }} \
    --token {{ influxdb2_admin_token }} \
    --force
  register: _setup
  failed_when:
    - _setup.rc != 0
    - '"has already been set up" not in _setup.stderr'
  changed_when: _setup.rc == 0

- name: InfluxDB2 - Ensure organizations exist
  ansible.builtin.command: influx org create \
    --host "{{ influxdb2_host }}" \
    --name "{{ item.name }}" \
    --description "{{ item.description | d('') }}"
  loop: "{{ influxdb2_orgs }}"
  loop_control:
    label: "{{ item.name }}"
  register: _org
  failed_when:
    - _org.rc != 0
    - '"already exists" not in _org.stderr'
  changed_when: _org.rc == 0

- name: InfluxDB2 - Ensure users exist
  ansible.builtin.command: influx user create \
    --host "{{ influxdb2_host }}" \
    --name "{{ item.name }}" \
    --org "{{ item.org }}" \
    --password "{{ item.password }}"
  loop: "{{ influxdb2_users }}"
  loop_control:
    label: "{{ item.name }}"
  register: _user
  failed_when:
    - _user.rc != 0
    - '"already exists" not in _user.stderr'
  changed_when: _user.rc == 0

- name: InfluxDB2 - Ensure buckets exist
  ansible.builtin.command: influx bucket create \
    --host "{{ influxdb2_host }}" \
    --name "{{ item.name }}" \
    --description "{{ item.description | d('') }}" \
    --org "{{ item.org }}" \
    --retention "{{ item.retention | d(0) }}"
  loop: "{{ influxdb2_buckets }}"
  loop_control:
    label: "{{ item.name }}"
  register: _bucket
  failed_when:
    - _bucket.rc != 0
    - '"already exists" not in _bucket.stderr'
  changed_when: _bucket.rc == 0
