---
- name: InfluxDB2 - Install dependencies
  ansible.builtin.package:
    name: "{{ influxdb2_dependencies }}"
    state: present
    update_cache: true

- name: InfluxDB2 - Add InfluxData APT signing key
  ansible.builtin.apt_key:
    state: present
    url: "{{ influxdb2_signing_key }}"

- name: InfluxDB2 - Add InfluxData APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ influxdb2_repository }}"
    state: present

- name: InfluxDB2 - Install InfluxDB packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ influxdb2_packages }}"

- name: InfluxDB2 - Create InfluxDB default environment file
  ansible.builtin.template:
    src: etc/default/influxdb2.j2
    dest: "{{ influxdb2_env_file }}"
    owner: root
    group: root
    mode: 0644
  #  notify: Restart InfluxDB

#
#- name: setup | Setup InfluxDB configuration file
#  ansible.builtin.template:
#    dest: "{{ influxdb_config_path }}/config.yml"
#    group: influxdb
#    mode: 0644
#    owner: influxdb
#    src: etc/influxdb/config.yml.j2
#  notify: Restart InfluxDB
#
#- name: setup | Ensure InfluxDB service is in the desired state
#  ansible.builtin.service:
#    enabled: "{{ influxdb_service_enabled }}"
#    name: "{{ influxdb_service_name }}"
#    state: "{{ influxdb_service_state }}"
#
## - name: Ensure InfluxDB service is in the desired state
##   ansible.builtin.service:
##     name: "{{ influxdb_service_name }}"
##     state: started
