---
- name: InfluxDB2 - Install dependencies
  ansible.builtin.package:
    name: "{{ influxdb2_dependencies }}"
    state: present
    update_cache: true

- name: InfluxDB2 - Add APT signing key
  ansible.builtin.apt_key:
    state: present
    url: "{{ influxdb2_signing_key }}"

- name: InfluxDB2 - Add APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ influxdb2_repository }}"
    state: present

- name: InfluxDB2 - Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ influxdb2_packages }}"

- name: InfluxDB2 - Create bolt path
  ansible.builtin.file:
    state: directory
    owner: influxdb
    group: influxdb
    mode: 0750
    path: "{{ influxdb2_bolt_path | dirname }}"

- name: InfluxDB2 - Create engine path
  ansible.builtin.file:
    state: directory
    owner: influxdb
    group: influxdb
    mode: 0750
    path: "{{ influxdb2_engine_path }}"

- name: InfluxDB2 - Create default environment file
  ansible.builtin.template:
    src: etc/default/influxdb2.j2
    dest: "{{ influxdb2_env_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart InfluxDB

- name: InfluxDB2 - Install configuration file
  ansible.builtin.template:
    dest: "{{ influxdb2_config_file }}"
    owner: root
    group: root
    mode: 0644
    src: etc/influxdb/config.yml.j2
  notify: Restart InfluxDB
#
#- name: setup | Ensure InfluxDB service is in the desired state
#  ansible.builtin.service:
#    enabled: "{{ influxdb_service_enabled }}"
#    name: "{{ influxdb_service_name }}"
#    state: "{{ influxdb_service_state }}"
#
## - name: Ensure InfluxDB service is in the desired state
##   ansible.builtin.service:
##     name: "{{ influxdb_service_name }}"
##     state: started
